x-airflow-common: &airflow-common
  image: apache/airflow:2.7.3
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://etl_user:etl_password@postgres:5432/financial_db
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    TICKER: GOOGL
    PERIOD: 2y
  volumes:
    - ./dags:/opt/airflow/dags
    - ./etl:/opt/airflow/etl
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data          # ← ajouter
    - ./requirements-airflow.txt:/requirements.txt
  depends_on:
    postgres:
      condition: service_healthy
  user: "${AIRFLOW_UID:-50000}:0"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      POSTGRES_DB: financial_db
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=trust"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "etl_user", "-d", "financial_db"]
      interval: 10s
      retries: 5

  airflow-init:
    <<: *airflow-common
    command: bash -c "pip install -r /requirements.txt && airflow db migrate && airflow users create --username admin --password admin123 --firstname Admin --lastname User --role Admin --email admin@financial-etl.com"
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    command: bash -c "pip install -r /requirements.txt && airflow webserver"
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: bash -c "pip install -r /requirements.txt && airflow scheduler"
    restart: always

  dashboard:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./dashboard:/app
      - ./requirements.txt:/requirements.txt
    command: bash -c "pip install -r /requirements.txt && python app.py"
    ports:
      - "8050:8050"
    env_file: .env
    depends_on:
      - postgres

volumes:
  postgres_data: